### ISSUE TITLE
What do I need to run this powershell?

### ISSUE THREAD

**Issue by screado** [box-community/box-powershell-sdk-v2#3]
Hi,

I see that there is a reference to the registry keys in the box.psm1. However the sdk v2 I installed on windows does not create that entry.

Can you post a link to what needs to be installed to run this script?

**Comment by jwhitwo** [comment]
You could run the cmdlets below to get the registry entries created.  Note - creating the registry entries requires admin rights.

$c_id = "<your client ID>"
$c_secret = "<your client secret>"

$code = New-BoxoAUTHCode -clientID $c_id

New-BoxAccessTokens -clientID $c_id -client_secret $c_secret -code $code
